name: ci

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write  # nécessaire pour pousser sur gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache pip & mkdocs cache
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ runner.os }}-${{ hashFiles('**/mkdocs.yml') }}
          path: |
            ~/.cache/pip
            ~/.cache/mkdocs
          restore-keys: |
            mkdocs-material-

      - name: Install MkDocs + theme + plugins
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocs-minify-plugin mkdocs-macros-plugin

      - name: Deploy to gh-pages
        run: mkdocs gh-deploy --force
